###
@FileStorage_HostAddress = https://localhost:7127

GET {{FileStorage_HostAddress}}/api/files/get-id-by-hash/
Content-Type: application/json

"qwerty"

###

GET{{FileStorage_HostAddress}}/api/files/get-by-id/
Content-Type: application/json 
Accept: application/octet-stream

"01fe7e27-93a1-4e99-87c3-507e2c7a806f"

